server:
  port: 8085
  servlet:
    context-path: /

management:
  server:
    port: 8185
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: mappings
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  liquibase:
    default-schema: account
    change-log: db.changelog/db.changelog-master.yaml
    enabled: ${LIQUIBASE_ENABLED:true}
    drop-first: ${LIQUIBASE_DROP_FIRST:false}
  application:
    name: account-app
